language: elixir
elixir:
  - 1.4.0
  - 1.4.5
  - 1.5.0
  - 1.6.0
otp_release:
  - 18.3
  - 19.2
matrix:
  include:
    - elixir: 1.4.5
      otp_release: 20.0
    - elixir: 1.5.0
      otp_release: 20.0
    - elixir: 1.5.1
      otp_release: 20.0
    - elixir: 1.6.0
      otp_release: 20.0
  exclude:
    - elixir: 1.6.0
      otp_release: 18.3
sudo: false
script:
  - mix espec
notifications:
  recipients:
    - swolf.dev@gmail.com
