language: elixir
sudo: false
cache:
  directories:
    - deps/
    - _build/

elixir:
  - 1.6.0
  - 1.6.6
  - 1.7.0
  - 1.7.4

otp_release:
  - 20.0
  - 20.3
  - 21.0
  - 21.1.1

env:
  - MIX_ENV=test
stages:
  - name: test
    if: NOT branch =~ ^wip/
  - name: docs
    if: branch = master
  - name: publish
    if: branch = master AND tag =~ ^v

jobs:
  exclude:
    - elixir: 1.6.0
      otp_release: 21.0
    - elixir: 1.6.0
      otp_release: 21.1.1

  include:
    - stage: test
      script: mix coveralls.travis
    - stage: docs
      script: mix hex.publish docs
      elixir: 1.7.4
      otp_release: 21.1.1
      env:
        - MIX_ENV=dev
    - stage: publish
      script: mix hex.publish package
      elixir: 1.7.4
      otp_release: 21.1.1
      env:
        - MIX_ENV=prod

notifications:
  recipients:
    - swolf.dev@gmail.com
