language: elixir
cache:
  directories:
    - deps/
    - _build/

elixir:
  - 1.6.0
  - 1.6.6
  - 1.7.0
  - 1.7.4

otp_release:
  - 20.0
  - 20.3
  - 21.0
  - 21.1.1

env:
  - MIX_ENV=test

matrix:
  exclude:
    - elixir: 1.6.0
      otp_release: 21.0
    - elixir: 1.6.0
      otp_release: 21.1.1

sudo: false

script:
  - mix coveralls.travis

notifications:
  recipients:
    - swolf.dev@gmail.com
