language: elixir

elixir:
  - 1.5.0
  - 1.5.1
  - 1.6.0
  - 1.6.1
  - 1.6.2
  - 1.6.3

otp_release:
  - 19.2
  - 20.0
  - 20.1

env:
  - MIX_ENV=test

sudo: false

script:
  - mix coveralls.travis

notifications:
  recipients:
    - swolf.dev@gmail.com
