name: Release

on:
  release:
    types: [published]

jobs:
  publish_to_hex:
    name: Publish to Hex.pm
    runs-on: ubuntu-latest
    container: hexpm/elixir:1.11.0-erlang-23.0.2-alpine-3.11.6
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
